### PR TITLE
Bugfix/entitieswith

### LINKED ISSUE #22: EntitiesWith does not return appropriate entities when multiple args are provided
Branch [bugfix/entitieswith](https://github.com/babsnbabs/babs-ecs/tree/bugfix/entitieswith) has reproduction steps for this bug in a unit test.

Repro:

- Create entity
- Create Component 1
- Create Component 2
- Add Component 1&2 to entity
- Attempt to retrieve entity via EntitiesWith(Component1, Component2)

EntitiesWith will return 0 results, should return 1 result with our entity.

### LINKED ISSUE #23: EntitiesWith should not return a vector of pointers
Currently we need to execute the following work around when iterating over entities that are returned from EntitiesWith:

```
std::vector<Entity *> entities = this->ecs->EntitiesWith(Graphic(), Position());

for (Entity* entity : entities)
{
	Entity convertedEntity = *entity;
	Graphic position = this->ecs->GetComponent(convertedEntity, Position());
	Graphic graphic = this->ecs->GetComponent(convertedEntity, Graphic());

        // {...}
}
```

Since we want consumers to be able to modify entities, GetComponent needs an overload to accept an Entity pointer instead of requiring consumers to convert it into a non-pointer before use.

### PR DESCRIPTION
**Pull request by misnor**
Closes #22 
Closes #23

- Fixes EntitiesWith not working with multiple types
- Fixes EntitiesWith returning a vector of pointers

Also made a few modifications on types - for example Entity took in a uint32_t in the constructor but its internal type was a signed int32_t. Same deal with entityIndex in ECS.

### CODE REVIEW

File: src/manager_tests.cpp [hunk 1]
```diff
@@ -23,154 +23,176 @@ struct Health
```
Comment (misnor) [inline src/manager_tests.cpp]: I tabbified this document as it was all jacked up in GitHub code review, the test i added is at the very bottom.
